// src/ui/GameBoard.vue
<template>
  <div class="p-6 space-y-3" v-if="room">
    <h1 class="text-3xl font-extrabold">UNO (Online)</h1>

    <div><b>Room:</b> {{ roomId }}</div>

    <div class="flex items-center gap-2">
      <div><b>Code:</b> <code>{{ room.code ?? "—" }}</code></div>
      <button
        v-if="room.code"
        @click="copyCode"
        class="px-2 py-1 text-sm rounded border"
      >
        Copy
      </button>
    </div>

    <div><b>Status:</b> {{ room.status }}</div>
    <div>
      <b>Turn:</b>
      {{ room.status === "finished" ? "—" : (isMyTurn ? "You" : (room.currentTurn ?? "—")) }}
    </div>
    <div><b>Players:</b> {{ players.map(p => p.displayName).join(", ") }}</div>

    <!-- Lobby or finished → Start button for host -->
    <div class="mt-2" v-if="room.status === 'lobby' || room.status === 'finished'">
      <button
        v-if="computedIsHost"
        class="px-4 py-2 rounded bg-emerald-600 text-white disabled:opacity-50"
        :disabled="players.length < 2"
        :title="players.length < 2 ? 'Need at least 2 players' : 'Start game'"
        @click="startGameClient(roomId)"
      >
        Start game
      </button>
      <div v-else>Waiting for host to start…</div>
    </div>

    <template v-if="room.status === 'playing'">
      <div class="mt-2 flex items-center gap-3">
        <div class="text-sm font-semibold">Top card:</div>
        <CardView v-if="top" :card="top" size="lg" />

        <!-- Current color badge (for wild / +4) -->
        <div
          v-if="topChosenColor"
          class="ml-2 px-2 py-1 rounded text-sm font-semibold border"
          :title="'Current color chosen for wild'"
          :style="{
            background:
              topChosenColor === 'red' ? '#fee2e2' :
              topChosenColor === 'yellow' ? '#fef9c3' :
              topChosenColor === 'green' ? '#dcfce7' :
              '#dbeafe'
          }"
        >
          Current color: {{ topChosenColor }}
        </div>

        <!-- Pending draw info (stacking) -->
        <div
          v-if="pendingDrawInfo"
          class="ml-2 px-2 py-1 rounded text-sm font-semibold border"
        >
          {{ pendingDrawInfo.type === 'draw4' ? '+4' : '+2' }} stack: draw {{ pendingDrawInfo.n }}
        </div>
      </div>

      <div class="mt-3 flex items-center gap-2">
        <button
          @click="onDraw"
          :disabled="!isMyTurn"
          class="px-4 py-2 rounded bg-blue-600 text-white disabled:opacity-50"
          :title="pendingDrawInfo
            ? `Draw ${pendingDrawInfo.n} and pass`
            : (youHavePlayable ? 'You already have a playable card' : 'Draw one')"
        >
          {{ pendingDrawInfo ? `Draw ${pendingDrawInfo.n}` : "Draw" }}
        </button>

        <!-- End turn shows only during number-chaining -->
        <button
          v-if="chainingActive"
          @click="onEndTurn"
          class="px-4 py-2 rounded bg-gray-700 text-white"
          title="Finish your number chain and pass the turn"
        >
          End turn
        </button>
      </div>

      <div class="mt-4">
        <h3 class="font-semibold mb-1">Your hand ({{ myHand.length }})</h3>

        <!-- Inline wild picker -->
        <div v-if="pendingWild" class="mb-2 flex items-center gap-2">
          <span class="text-sm">Pick color:</span>
          <button type="button" @click="playChosenWild('red')" class="px-3 py-1 rounded border" style="background:#ef4444;color:white">red</button>
          <button type="button" @click="playChosenWild('yellow')" class="px-3 py-1 rounded border" style="background:#eab308">yellow</button>
          <button type="button" @click="playChosenWild('green')" class="px-3 py-1 rounded border" style="background:#22c55e;color:white">green</button>
          <button type="button" @click="playChosenWild('blue')" class="px-3 py-1 rounded border" style="background:#3b82f6;color:white">blue</button>
          <button type="button" @click="pendingWild = null" class="px-2 py-1 rounded border" title="Cancel">Cancel</button>
        </div>

        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="(c, i) in myHand"
            :key="i"
            type="button"
            @click="onPlayCard(c, i)"
            :disabled="!cardClickable(c)"
            :aria-disabled="!cardClickable(c)"
            class="relative inline-block p-0 border-0 bg-transparent"
            :class="cardClickable(c) ? 'cursor-pointer' : 'opacity-60 cursor-not-allowed'"
            :title="!isMyTurn
              ? 'Not your turn'
              : pendingType
                ? (pendingType === 'draw4' ? 'Only +4 can be played (or Draw)' : 'Only +2 can be played (or Draw)')
                : undefined"
          >
            <CardView :card="c" size="md" />
            <span class="absolute inset-0" />
          </button>
        </div>
      </div>
    </template>

    <!-- Win Screen -->
    <div
      v-if="room.status === 'finished'"
      class="mt-4 p-4 rounded-xl border bg-white/70 backdrop-blur"
    >
      <div class="text-xl font-bold mb-1">
        {{ winner ?? "A player" }} won!
      </div>
      <div class="text-sm text-gray-600 mb-3">
        Game over{{ topChosenColor ? ` — final color: ${topChosenColor}` : "" }}.
      </div>
      <button
        v-if="computedIsHost"
        class="px-4 py-2 rounded bg-emerald-600 text-white"
        @click="startGameClient(roomId)"
      >
        Start new game
      </button>
      <div v-else>Waiting for host to start a new game…</div>
    </div>
  </div>

  <div v-else class="p-6">Loading room…</div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from "vue";
import type { Card } from "../cards/Card";
import CardView from "../ui/CardView.vue"; // if your CardView is Vue; adjust path/extension as needed
import {
  subscribeOnlineGame,
  startGameClient,
  playCardOnline,
  drawOneOnline,
  endTurnOnline
} from "../services/OnlineGame";
import { matches } from "../cards/Rules";
import { auth } from "../firebase";

type Props = { roomId: string; isHost: boolean };
const props = defineProps<Props>();

const room = ref<any | null>(null);
const players = ref<any[]>([]);
const myHand = ref<Card[]>([]);
const pendingWild = ref<{ index: number; card: Card } | null>(null);

let unsubscribe: null | (() => void) = null;

onMounted(() => {
  unsubscribe = subscribeOnlineGame(props.roomId, {
    onRoom: (r: any) => (room.value = r),
    onPlayers: (p: any[]) => (players.value = p),
    onMyHand: (h: Card[]) => (myHand.value = h)
  });
});

onUnmounted(() => {
  if (unsubscribe) unsubscribe();
});

const top = computed<Card | null>(() => room.value?.topCard ?? null);
const myUid = computed(() => auth.currentUser?.uid ?? null);
const isMyTurn = computed(
  () => room.value?.currentTurn === myUid.value && room.value?.status === "playing"
);

// Host fallback: prop OR explicit host in room OR first joined player
const computedIsHost = computed(() =>
  props.isHost ||
  room.value?.hostUid === myUid.value ||
  (players.value.length > 0 && players.value[0]?.id === myUid.value)
);

// Pending stack / chaining awareness
const pendingType = computed<"draw2" | "draw4" | null>(() => (room.value?.pendingType ?? null));
const chainingActive = computed<boolean>(() => room.value?.chainPlayer === myUid.value && room.value?.chainValue !== null);

// Standard playable (when no pending stack)
const youHavePlayable = computed<boolean>(
  () => !!top.value && myHand.value.some(c => matches(top.value as Card, c))
);

const winner = computed<string | null>(() => {
  if (!room.value?.winnerUid) return null;
  const w = players.value.find(p => p.id === room.value!.winnerUid);
  return w?.displayName ?? room.value!.winnerUid;
});

const topChosenColor = computed<"red" | "yellow" | "green" | "blue" | null>(() => {
  const t = top.value as any;
  if (!t || t.kind !== "wild") return null;
  return t.chosenColor ?? null;
});

async function playChosenWild(color: "red" | "yellow" | "green" | "blue") {
  const pw = pendingWild.value;
  if (!pw) return;
  const toPlay: any = { ...pw.card, chosenColor: color };
  try {
    await playCardOnline(props.roomId, toPlay);
  } catch (e: any) {
    alert(e?.message ?? String(e));
  } finally {
    pendingWild.value = null;
  }
}

// During a pending stack, ONLY allow stacking the same type.
function canStackSame(c: Card) {
  if (pendingType.value === "draw2") {
    return c.kind === "action" && c.action === "draw2";
  }
  if (pendingType.value === "draw4") {
    return c.kind === "wild" && c.action === "wildDraw4";
  }
  return false;
}

// During number-chaining, allow same-number plays regardless of matches(top, c).
function canChainNumber(c: Card) {
  return chainingActive.value && c.kind === "number" && c.value === room.value?.chainValue;
}

const pendingDrawInfo = computed<null | { n: number; type: "draw2" | "draw4" | null }>(() => {
  return room.value?.pendingDraw
    ? { n: room.value.pendingDraw as number, type: room.value.pendingType as any }
    : null;
});

function cardClickable(c: Card) {
  if (!isMyTurn.value) return false;
  if (pendingType.value) {
    return canStackSame(c);
  }
  const looksPlayable = !!top.value && matches(top.value as Card, c);
  return looksPlayable || canChainNumber(c);
}

async function onPlayCard(c: Card, i: number) {
  if (!cardClickable(c)) return;
  const anyCard = c as any;
  if (c.kind === "wild" && !anyCard.chosenColor) {
    pendingWild.value = { index: i, card: c };
    return;
  }
  try {
    await playCardOnline(props.roomId, c);
  } catch (e: any) {
    alert(e?.message ?? String(e));
  }
}

async function onDraw() {
  try {
    await drawOneOnline(props.roomId);
  } catch (e: any) {
    alert(e?.message ?? String(e));
  }
}

async function onEndTurn() {
  try {
    await endTurnOnline(props.roomId);
  } catch (e: any) {
    alert(e?.message ?? String(e));
  }
}

async function copyCode() {
  try {
    if (room.value?.code) {
      await navigator.clipboard.writeText(room.value.code);
    }
  } catch {
    // no-op
  }
}
</script>

// src/react/components/GameBoard.tsx
import React, { useEffect, useState, useMemo } from "react";
import { useSelector } from "react-redux";
import type { RootState } from "../../store/store";
import { startListeningToRoom } from "../../store/streams";
import { auth } from "../../firebase";
import { matches } from "../../cards/Rules";
import type { Card } from "../../cards/Card";
import { playCardOnline, drawOneOnline, endTurnOnline, startGameClient } from "../../services/OnlineGame";
import { CardView } from "./CardView";

interface Props { roomId: string; isHost: boolean; }

export const GameBoard: React.FC<Props> = ({ roomId, isHost }) => {
  const room = useSelector((s: RootState) => s.game.room);
  const players = useSelector((s: RootState) => s.game.players);
  const myHand = useSelector((s: RootState) => s.game.myHand);
  const [pendingWild, setPendingWild] = useState<{ index: number; card: Card } | null>(null);
  const [stop, setStop] = useState<null | (() => void)>(null);

  useEffect(() => {
    if (stop) stop();
    const unsub = startListeningToRoom(roomId);
    setStop(() => unsub);
    return () => { if (unsub) unsub(); };
  }, [roomId]);

  const myUid = auth.currentUser?.uid;
  const top = room?.topCard as Card | undefined;
  const isMyTurn = room?.currentTurn === myUid && room?.status === "playing";
  const computedIsHost = isHost || room?.hostUid === myUid || (players.length > 0 && players[0].id === myUid);

  const pendingType = room?.pendingType as ("draw2" | "draw4" | null);
  const chainingActive = room?.chainPlayer === myUid && room?.chainValue !== null;

  function canStackSame(c: Card) {
    if (pendingType === "draw2") return c.kind === "action" && c.action === "draw2";
    if (pendingType === "draw4") return c.kind === "wild" && c.action === "wildDraw4";
    return false;
  }
  function canChainNumber(c: Card) {
    return chainingActive && c.kind === "number" && c.value === room?.chainValue;
  }
  function cardClickable(c: Card) {
    if (!isMyTurn) return false;
    if (pendingType) return canStackSame(c);
    return (!!top && matches(top, c)) || canChainNumber(c);
  }

  const pendingDrawInfo = useMemo(() => {
    return room?.pendingDraw ? { n: room.pendingDraw as number, type: pendingType } : null;
  }, [room?.pendingDraw, pendingType]);

  const topChosenColor = useMemo(() => {
    if (top && top.kind === "wild") return (top as any).chosenColor ?? null;
    return null;
  }, [top]);

  async function playChosenWild(color: "red" | "yellow" | "green" | "blue") {
    const pw = pendingWild;
    if (!pw) return;
    const toPlay: any = { ...pw.card, chosenColor: color };
    try { await playCardOnline(roomId, toPlay); } catch (e:any) { alert(e.message ?? String(e)); }
    setPendingWild(null);
  }

  async function onPlayCard(c: Card, i: number) {
    if (!cardClickable(c)) return;
    if (c.kind === "wild" && !(c as any).chosenColor) {
      setPendingWild({ index: i, card: c });
      return;
    }
    try { await playCardOnline(roomId, c); } catch (e:any) { alert(e.message ?? String(e)); }
  }
  async function onDraw() { try { await drawOneOnline(roomId); } catch (e:any) { alert(e.message ?? String(e)); } }
  async function onEndTurn() { try { await endTurnOnline(roomId); } catch (e:any) { alert(e.message ?? String(e)); } }
  async function onStartGame() { try { await startGameClient(roomId); } catch (e:any) { alert(e.message ?? String(e)); } }

  const winnerUid = room?.winnerUid;
  const winnerName = winnerUid ? (players.find(p => p.id === winnerUid)?.displayName || winnerUid) : null;

  return (
    <div style={{ padding: 16 }}>
      <h1 style={{ fontSize: 28, fontWeight: 800 }}>UNO (React)</h1>
      <div><b>Room:</b> {roomId}</div>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 4 }}>
        <div><b>Code:</b> <code>{room?.code ?? "—"}</code></div>
        {room?.code && (
          <button
            onClick={() => navigator.clipboard?.writeText(room.code as string).catch(() => {})}
            style={{ padding: "2px 8px", border: "1px solid #ccc", borderRadius: 4, fontSize: 12, cursor: "pointer" }}
            title="Copy invite code"
          >
            Copy
          </button>
        )}
      </div>
      <div><b>Status:</b> {room?.status}</div>
      <div><b>Turn:</b> {room?.status === "finished" ? "—" : (isMyTurn ? "You" : room?.currentTurn ?? "—")}</div>
      <div><b>Players:</b> {players.map(p => p.displayName).join(", ")}</div>

      {(room?.status === "lobby" || room?.status === "finished") && (
        <div style={{ marginTop: 12 }}>
          {computedIsHost ? (
            <button onClick={onStartGame} disabled={players.length < 2} style={btnPrimary}>
              Start game
            </button>
          ) : (
            <div>Waiting for host to start…</div>
          )}
        </div>
      )}

      {room?.status === "playing" && (
        <>
          <div style={{ marginTop: 16, display: "flex", alignItems: "center", gap: 12 }}>
            <div style={{ fontWeight: 600 }}>Top card:</div>
            {top && (
              <CardView card={top} size="md" disabled title="Top card" />
            )}
            {topChosenColor && (
              <div style={{ padding: "2px 6px", border: "1px solid #ccc", borderRadius: 4, fontSize: 12 }}>
                Current color: {topChosenColor}
              </div>
            )}
            {pendingDrawInfo && (
              <div style={{ padding: "2px 6px", border: "1px solid #ccc", borderRadius: 4, fontSize: 12 }}>
                {pendingDrawInfo.type === "draw4" ? "+4" : "+2"} stack: draw {pendingDrawInfo.n}
              </div>
            )}
          </div>

          <div style={{ marginTop: 12, display: "flex", gap: 8 }}>
            <button onClick={onDraw} disabled={!isMyTurn} style={btnBlue}>{pendingDrawInfo ? `Draw ${pendingDrawInfo.n}` : "Draw"}</button>
            {chainingActive && (
              <button onClick={onEndTurn} style={btnGray}>End Turn</button>
            )}
          </div>

            {pendingWild && (
              <div style={{ marginTop: 12, display: "flex", gap: 8, alignItems: "center" }}>
                <span style={{ fontSize: 12 }}>Pick color:</span>
                {(["red","yellow","green","blue"] as const).map(c => (
                  <button key={c} onClick={() => playChosenWild(c)} style={{ ...btnSmall, background: colorBg[c], color: c === "yellow" ? "#000" : "#fff" }}>{c}</button>
                ))}
                <button onClick={() => setPendingWild(null)} style={btnSmall}>Cancel</button>
              </div>
            )}

          <div style={{ marginTop: 16 }}>
            <h3 style={{ fontWeight: 600 }}>Your hand ({myHand.length})</h3>
            <div style={{ display: "flex", flexWrap: "wrap" }}>
              {myHand.map((c, i) => {
                const playable = cardClickable(c);
                return (
                  <CardView
                    key={i}
                    card={c}
                    size="lg"
                    disabled={!playable}
                    onPlay={() => onPlayCard(c, i)}
                    title={playable ? "Play" : "Not playable"}
                  />
                );
              })}
            </div>
          </div>
        </>
      )}

      {room?.status === "finished" && (
        <div style={{ marginTop: 20, padding: 12, border: "1px solid #ccc", borderRadius: 8 }}>
          <div style={{ fontSize: 20, fontWeight: 700 }}>🎉 {winnerName ?? "A player"} won!</div>
          <div style={{ fontSize: 12, marginTop: 4 }}>Game over{topChosenColor ? ` — final color: ${topChosenColor}` : ""}.</div>
          {computedIsHost ? (
            <button onClick={onStartGame} style={{ ...btnPrimary, marginTop: 8 }}>Start new game</button>
          ) : (
            <div style={{ marginTop: 8 }}>Waiting for host to start a new game…</div>
          )}
        </div>
      )}

      <div style={{ marginTop: 24, fontSize: 11, opacity: 0.6 }}>Build: {typeof __BUILD_TIME__ !== 'undefined' ? __BUILD_TIME__ : 'dev'}</div>
    </div>
  );
};

declare const __BUILD_TIME__: string | undefined;

const btnPrimary: React.CSSProperties = { padding: "6px 12px", background: "#059669", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer" };
const btnBlue: React.CSSProperties = { padding: "6px 12px", background: "#2563eb", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer" };
const btnGray: React.CSSProperties = { padding: "6px 12px", background: "#374151", color: "#fff", border: "none", borderRadius: 6, cursor: "pointer" };
const btnSmall: React.CSSProperties = { padding: "4px 8px", background: "#6b7280", color: "#fff", border: "none", borderRadius: 4, cursor: "pointer", fontSize: 12 };
const cardStyle: React.CSSProperties = { margin: 4, padding: 6, minWidth: 70, border: "1px solid #999", borderRadius: 6, background: "#fff" };
const colorBg: Record<string,string> = { red: "#ef4444", yellow: "#eab308", green: "#22c55e", blue: "#3b82f6" };
